version: '1.0'
services:

  db:
    container_name: db
    image: mysql:latest
    networks:
      - ci-network
    environment:
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    
  front-app:
    build:
      context: .
    container_name: ci-angular
    image: likeaboos/angular-ci:frontend
    ports:
      - "8888:80"
    networks:
      - ci-network

  app:
    build:
      context: .
    container_name: ci-spring
    image: likeaboos/ci:latest
    ports:
      - "8089:8089"
    networks:
      - ci-network
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USERNAME=new_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=achatdb
      - MYSQL_PORT=3306
      

networks:
  ci-network:
    name: ci-network

volumes:
  my-db:
